[package]
name = "minigit"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
bpaf = { version = "0.9.27", features = ["derive"] }
hex = "0.4.3"
itertools = "0.15.0"
sha1 = "0.11.0"
strum = { version = "0.28.0", features = ["derive"] }

[dev-dependencies]
tar = "0.4.46"
tempfile = "3.27.0"
